services:
  postgis:
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-geoai}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-geoai}
      - POSTGRES_DB=${POSTGRES_DB:-geoai}
    ports:
      - 5432:5432

